/*
  File autogenerated by gengetopt version 2.22.6
  generated with the following command:
  gengetopt -F cmdline_sissiz --unamed-opts --no-handle-version --no-handle-help --no-handle-error 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline_sissiz.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: " CMDLINE_PARSER_PACKAGE " [OPTIONS]... [FILES]...";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "  -r, --nossr                   No site specific rates  (default=off)",
  "  -f, --flanks=INT              Flanking sites",
  "  -o, --outfile=STRING          Output filename",
  "  -n, --num-samples=INT         Number of samples",
  "  -m, --num-samples-regression=INT\n                                Number of samples in regression",
  "  -p, --precision=DOUBLE        Cut-off for mononucleotide content (Euclidean\n                                  distance of frequency vector)",
  "  -s, --simulate                Simulate only  (default=off)",
  "  -v, --verbose                 verbose  (default=off)",
  "  -i, --mono                    Mononucleotide  (default=off)",
  "  -d, --di                      Mononucleotide  (default=on)",
  "  -q, --dna                     Print Us or Ts  (default=on)",
  "  -u, --rna                     Print Us or Ts  (default=off)",
  "  -t, --tstv                    Transition/Transversion ratio  (default=on)",
  "  -k, --kappa=FLOAT             kappa parameter",
  "  -g, --gamma=INT               Categories for gamma for kappa ML estimation",
  "  -b, --print-tree              Print estimated tree   (default=off)",
  "  -x, --print-rates             Print rates to file (debugging)  (default=off)",
  "      --clustal                 Output format CLUSTAL W  (default=on)",
  "      --maf                     Output format MAF  (default=off)",
  "      --fasta                   Output format FASTA  (default=off)",
  "  -a, --oldAliEn                use old alifold energies (with gaps)\n                                  (default=off)",
  "  -j, --ribo                    use ribosum matrices  (default=off)",
  "      --shape=file1,file2       Use SHAPE reactivity data to guide structure\n                                  predicitons =file1,file2",
  "      --shapeMethod=D[mX][bY]   Specify the method how to convert SHAPE\n                                  reactivity data to pseudo energy\n                                  contributions =D[mX][bY]",
  "  -y, --seed_with_pID           Seed with process ID (default=off)\n                                  (default=off)",
  "  -z, --print_seeds             Print seed values  (default=off)  (default=off)",
  "      --read_seeds=file1,file2  set seed value(s) ={seed1(,seed2)}",
  "      --sci                     Calculate SCI  (default=off)",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
  , ARG_FLOAT
  , ARG_DOUBLE
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->nossr_given = 0 ;
  args_info->flanks_given = 0 ;
  args_info->outfile_given = 0 ;
  args_info->num_samples_given = 0 ;
  args_info->num_samples_regression_given = 0 ;
  args_info->precision_given = 0 ;
  args_info->simulate_given = 0 ;
  args_info->verbose_given = 0 ;
  args_info->mono_given = 0 ;
  args_info->di_given = 0 ;
  args_info->dna_given = 0 ;
  args_info->rna_given = 0 ;
  args_info->tstv_given = 0 ;
  args_info->kappa_given = 0 ;
  args_info->gamma_given = 0 ;
  args_info->print_tree_given = 0 ;
  args_info->print_rates_given = 0 ;
  args_info->clustal_given = 0 ;
  args_info->maf_given = 0 ;
  args_info->fasta_given = 0 ;
  args_info->oldAliEn_given = 0 ;
  args_info->ribo_given = 0 ;
  args_info->shape_given = 0 ;
  args_info->shapeMethod_given = 0 ;
  args_info->seed_with_pID_given = 0 ;
  args_info->print_seeds_given = 0 ;
  args_info->read_seeds_given = 0 ;
  args_info->sci_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->nossr_flag = 0;
  args_info->flanks_orig = NULL;
  args_info->outfile_arg = NULL;
  args_info->outfile_orig = NULL;
  args_info->num_samples_orig = NULL;
  args_info->num_samples_regression_orig = NULL;
  args_info->precision_orig = NULL;
  args_info->simulate_flag = 0;
  args_info->verbose_flag = 0;
  args_info->mono_flag = 0;
  args_info->di_flag = 1;
  args_info->dna_flag = 1;
  args_info->rna_flag = 0;
  args_info->tstv_flag = 1;
  args_info->kappa_orig = NULL;
  args_info->gamma_orig = NULL;
  args_info->print_tree_flag = 0;
  args_info->print_rates_flag = 0;
  args_info->clustal_flag = 1;
  args_info->maf_flag = 0;
  args_info->fasta_flag = 0;
  args_info->oldAliEn_flag = 0;
  args_info->ribo_flag = 0;
  args_info->shape_arg = NULL;
  args_info->shape_orig = NULL;
  args_info->shapeMethod_arg = NULL;
  args_info->shapeMethod_orig = NULL;
  args_info->seed_with_pID_flag = 0;
  args_info->print_seeds_flag = 0;
  args_info->read_seeds_arg = NULL;
  args_info->read_seeds_orig = NULL;
  args_info->sci_flag = 0;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->nossr_help = gengetopt_args_info_help[2] ;
  args_info->flanks_help = gengetopt_args_info_help[3] ;
  args_info->outfile_help = gengetopt_args_info_help[4] ;
  args_info->num_samples_help = gengetopt_args_info_help[5] ;
  args_info->num_samples_regression_help = gengetopt_args_info_help[6] ;
  args_info->precision_help = gengetopt_args_info_help[7] ;
  args_info->simulate_help = gengetopt_args_info_help[8] ;
  args_info->verbose_help = gengetopt_args_info_help[9] ;
  args_info->mono_help = gengetopt_args_info_help[10] ;
  args_info->di_help = gengetopt_args_info_help[11] ;
  args_info->dna_help = gengetopt_args_info_help[12] ;
  args_info->rna_help = gengetopt_args_info_help[13] ;
  args_info->tstv_help = gengetopt_args_info_help[14] ;
  args_info->kappa_help = gengetopt_args_info_help[15] ;
  args_info->gamma_help = gengetopt_args_info_help[16] ;
  args_info->print_tree_help = gengetopt_args_info_help[17] ;
  args_info->print_rates_help = gengetopt_args_info_help[18] ;
  args_info->clustal_help = gengetopt_args_info_help[19] ;
  args_info->maf_help = gengetopt_args_info_help[20] ;
  args_info->fasta_help = gengetopt_args_info_help[21] ;
  args_info->oldAliEn_help = gengetopt_args_info_help[22] ;
  args_info->ribo_help = gengetopt_args_info_help[23] ;
  args_info->shape_help = gengetopt_args_info_help[24] ;
  args_info->shape_min = 1;
  args_info->shape_max = 0;
  args_info->shapeMethod_help = gengetopt_args_info_help[25] ;
  args_info->seed_with_pID_help = gengetopt_args_info_help[26] ;
  args_info->print_seeds_help = gengetopt_args_info_help[27] ;
  args_info->read_seeds_help = gengetopt_args_info_help[28] ;
  args_info->read_seeds_min = 1;
  args_info->read_seeds_max = 0;
  args_info->sci_help = gengetopt_args_info_help[29] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}

/** @brief generic value variable */
union generic_value {
    int int_arg;
    float float_arg;
    double double_arg;
    char *string_arg;
    const char *default_string_arg;
};

/** @brief holds temporary values for multiple options */
struct generic_list
{
  union generic_value arg;
  char *orig;
  struct generic_list *next;
};

/**
 * @brief add a node at the head of the list 
 */
static void add_node(struct generic_list **list) {
  struct generic_list *new_node = (struct generic_list *) malloc (sizeof (struct generic_list));
  new_node->next = *list;
  *list = new_node;
  new_node->arg.string_arg = 0;
  new_node->orig = 0;
}


static void
free_multiple_string_field(unsigned int len, char ***arg, char ***orig)
{
  unsigned int i;
  if (*arg) {
    for (i = 0; i < len; ++i)
      {
        free_string_field(&((*arg)[i]));
        free_string_field(&((*orig)[i]));
      }
    free_string_field(&((*arg)[0])); /* free default string */

    free (*arg);
    *arg = 0;
    free (*orig);
    *orig = 0;
  }
}

static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->flanks_orig));
  free_string_field (&(args_info->outfile_arg));
  free_string_field (&(args_info->outfile_orig));
  free_string_field (&(args_info->num_samples_orig));
  free_string_field (&(args_info->num_samples_regression_orig));
  free_string_field (&(args_info->precision_orig));
  free_string_field (&(args_info->kappa_orig));
  free_string_field (&(args_info->gamma_orig));
  free_multiple_string_field (args_info->shape_given, &(args_info->shape_arg), &(args_info->shape_orig));
  free_string_field (&(args_info->shapeMethod_arg));
  free_string_field (&(args_info->shapeMethod_orig));
  free_multiple_string_field (args_info->read_seeds_given, &(args_info->read_seeds_arg), &(args_info->read_seeds_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}

static void
write_multiple_into_file(FILE *outfile, int len, const char *opt, char **arg, const char *values[])
{
  int i;
  
  for (i = 0; i < len; ++i)
    write_into_file(outfile, opt, (arg ? arg[i] : 0), values);
}

int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->nossr_given)
    write_into_file(outfile, "nossr", 0, 0 );
  if (args_info->flanks_given)
    write_into_file(outfile, "flanks", args_info->flanks_orig, 0);
  if (args_info->outfile_given)
    write_into_file(outfile, "outfile", args_info->outfile_orig, 0);
  if (args_info->num_samples_given)
    write_into_file(outfile, "num-samples", args_info->num_samples_orig, 0);
  if (args_info->num_samples_regression_given)
    write_into_file(outfile, "num-samples-regression", args_info->num_samples_regression_orig, 0);
  if (args_info->precision_given)
    write_into_file(outfile, "precision", args_info->precision_orig, 0);
  if (args_info->simulate_given)
    write_into_file(outfile, "simulate", 0, 0 );
  if (args_info->verbose_given)
    write_into_file(outfile, "verbose", 0, 0 );
  if (args_info->mono_given)
    write_into_file(outfile, "mono", 0, 0 );
  if (args_info->di_given)
    write_into_file(outfile, "di", 0, 0 );
  if (args_info->dna_given)
    write_into_file(outfile, "dna", 0, 0 );
  if (args_info->rna_given)
    write_into_file(outfile, "rna", 0, 0 );
  if (args_info->tstv_given)
    write_into_file(outfile, "tstv", 0, 0 );
  if (args_info->kappa_given)
    write_into_file(outfile, "kappa", args_info->kappa_orig, 0);
  if (args_info->gamma_given)
    write_into_file(outfile, "gamma", args_info->gamma_orig, 0);
  if (args_info->print_tree_given)
    write_into_file(outfile, "print-tree", 0, 0 );
  if (args_info->print_rates_given)
    write_into_file(outfile, "print-rates", 0, 0 );
  if (args_info->clustal_given)
    write_into_file(outfile, "clustal", 0, 0 );
  if (args_info->maf_given)
    write_into_file(outfile, "maf", 0, 0 );
  if (args_info->fasta_given)
    write_into_file(outfile, "fasta", 0, 0 );
  if (args_info->oldAliEn_given)
    write_into_file(outfile, "oldAliEn", 0, 0 );
  if (args_info->ribo_given)
    write_into_file(outfile, "ribo", 0, 0 );
  write_multiple_into_file(outfile, args_info->shape_given, "shape", args_info->shape_orig, 0);
  if (args_info->shapeMethod_given)
    write_into_file(outfile, "shapeMethod", args_info->shapeMethod_orig, 0);
  if (args_info->seed_with_pID_given)
    write_into_file(outfile, "seed_with_pID", 0, 0 );
  if (args_info->print_seeds_given)
    write_into_file(outfile, "print_seeds", 0, 0 );
  write_multiple_into_file(outfile, args_info->read_seeds_given, "read_seeds", args_info->read_seeds_orig, 0);
  if (args_info->sci_given)
    write_into_file(outfile, "sci", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static char *
get_multiple_arg_token(const char *arg)
{
  const char *tok;
  char *ret;
  size_t len, num_of_escape, i, j;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');
  num_of_escape = 0;

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
          ++num_of_escape;
        }
      else
        break;
    }

  if (tok)
    len = (size_t)(tok - arg + 1);
  else
    len = strlen (arg) + 1;

  len -= num_of_escape;

  ret = (char *) malloc (len);

  i = 0;
  j = 0;
  while (arg[i] && (j < len-1))
    {
      if (arg[i] == '\\' && 
	  arg[ i + 1 ] && 
	  arg[ i + 1 ] == ',')
        ++i;

      ret[j++] = arg[i++];
    }

  ret[len-1] = '\0';

  return ret;
}

static const char *
get_multiple_arg_token_next(const char *arg)
{
  const char *tok;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
        }
      else
        break;
    }

  if (! tok || strlen(tok) == 1)
    return 0;

  return tok+1;
}

static int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc);

int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc)
{
  int error_occurred = 0;

  if (option_given && (min > 0 || max > 0))
    {
      if (min > 0 && max > 0)
        {
          if (min == max)
            {
              /* specific occurrences */
              if (option_given != (unsigned int) min)
                {
                  fprintf (stderr, "%s: %s option occurrences must be %d\n",
                    prog_name, option_desc, min);
                  error_occurred = 1;
                }
            }
          else if (option_given < (unsigned int) min
                || option_given > (unsigned int) max)
            {
              /* range occurrences */
              fprintf (stderr, "%s: %s option occurrences must be between %d and %d\n",
                prog_name, option_desc, min, max);
              error_occurred = 1;
            }
        }
      else if (min > 0)
        {
          /* at least check */
          if (option_given < min)
            {
              fprintf (stderr, "%s: %s option occurrences must be at least %d\n",
                prog_name, option_desc, min);
              error_occurred = 1;
            }
        }
      else if (max > 0)
        {
          /* at most check */
          if (option_given > max)
            {
              fprintf (stderr, "%s: %s option occurrences must be at most %d\n",
                prog_name, option_desc, max);
              error_occurred = 1;
            }
        }
    }
    
  return error_occurred;
}
int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (check_multiple_option_occurrences(prog_name, args_info->shape_given, args_info->shape_min, args_info->shape_max, "'--shape'"))
     error_occurred = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->read_seeds_given, args_info->read_seeds_min, args_info->read_seeds_max, "'--read_seeds'"))
     error_occurred = 1;
  
  
  /* checks for dependences among options */
  if (args_info->shapeMethod_given && ! args_info->shape_given)
    {
      fprintf (stderr, "%s: '--shapeMethod' option depends on option 'shape'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }

  return error_occurred;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_FLOAT:
    if (val) *((float *)field) = (float)strtod (val, &stop_char);
    break;
  case ARG_DOUBLE:
    if (val) *((double *)field) = strtod (val, &stop_char);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_FLOAT:
  case ARG_DOUBLE:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}

/**
 * @brief store information about a multiple option in a temporary list
 * @param list where to (temporarily) store multiple options
 */
static
int update_multiple_arg_temp(struct generic_list **list,
               unsigned int *prev_given, const char *val,
               const char *possible_values[], const char *default_value,
               cmdline_parser_arg_type arg_type,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  /* store single arguments */
  char *multi_token;
  const char *multi_next;

  if (arg_type == ARG_NO) {
    (*prev_given)++;
    return 0; /* OK */
  }

  multi_token = get_multiple_arg_token(val);
  multi_next = get_multiple_arg_token_next (val);

  while (1)
    {
      add_node (list);
      if (update_arg((void *)&((*list)->arg), &((*list)->orig), 0,
          prev_given, multi_token, possible_values, default_value, 
          arg_type, 0, 1, 1, 1, long_opt, short_opt, additional_error)) {
        if (multi_token) free(multi_token);
        return 1; /* failure */
      }

      if (multi_next)
        {
          multi_token = get_multiple_arg_token(multi_next);
          multi_next = get_multiple_arg_token_next (multi_next);
        }
      else
        break;
    }

  return 0; /* OK */
}

/**
 * @brief free the passed list (including possible string argument)
 */
static
void free_list(struct generic_list *list, short string_arg)
{
  if (list) {
    struct generic_list *tmp;
    while (list)
      {
        tmp = list;
        if (string_arg && list->arg.string_arg)
          free (list->arg.string_arg);
        if (list->orig)
          free (list->orig);
        list = list->next;
        free (tmp);
      }
  }
}

/**
 * @brief updates a multiple option starting from the passed list
 */
static
void update_multiple_arg(void *field, char ***orig_field,
               unsigned int field_given, unsigned int prev_given, union generic_value *default_value,
               cmdline_parser_arg_type arg_type,
               struct generic_list *list)
{
  int i;
  struct generic_list *tmp;

  if (prev_given && list) {
    *orig_field = (char **) realloc (*orig_field, (field_given + prev_given) * sizeof (char *));

    switch(arg_type) {
    case ARG_INT:
      *((int **)field) = (int *)realloc (*((int **)field), (field_given + prev_given) * sizeof (int)); break;
    case ARG_FLOAT:
      *((float **)field) = (float *)realloc (*((float **)field), (field_given + prev_given) * sizeof (float)); break;
    case ARG_DOUBLE:
      *((double **)field) = (double *)realloc (*((double **)field), (field_given + prev_given) * sizeof (double)); break;
    case ARG_STRING:
      *((char ***)field) = (char **)realloc (*((char ***)field), (field_given + prev_given) * sizeof (char *)); break;
    default:
      break;
    };
    
    for (i = (prev_given - 1); i >= 0; --i)
      {
        tmp = list;
        
        switch(arg_type) {
        case ARG_INT:
          (*((int **)field))[i + field_given] = tmp->arg.int_arg; break;
        case ARG_FLOAT:
          (*((float **)field))[i + field_given] = tmp->arg.float_arg; break;
        case ARG_DOUBLE:
          (*((double **)field))[i + field_given] = tmp->arg.double_arg; break;
        case ARG_STRING:
          (*((char ***)field))[i + field_given] = tmp->arg.string_arg; break;
        default:
          break;
        }        
        (*orig_field) [i + field_given] = list->orig;
        list = list->next;
        free (tmp);
      }
  } else { /* set the default value */
    if (default_value && ! field_given) {
      switch(arg_type) {
      case ARG_INT:
        if (! *((int **)field)) {
          *((int **)field) = (int *)malloc (sizeof (int));
          (*((int **)field))[0] = default_value->int_arg; 
        }
        break;
      case ARG_FLOAT:
        if (! *((float **)field)) {
          *((float **)field) = (float *)malloc (sizeof (float));
          (*((float **)field))[0] = default_value->float_arg;
        }
        break;
      case ARG_DOUBLE:
        if (! *((double **)field)) {
          *((double **)field) = (double *)malloc (sizeof (double));
          (*((double **)field))[0] = default_value->double_arg;
        }
        break;
      case ARG_STRING:
        if (! *((char ***)field)) {
          *((char ***)field) = (char **)malloc (sizeof (char *));
          (*((char ***)field))[0] = gengetopt_strdup(default_value->string_arg);
        }
        break;
      default: break;
      }
      if (!(*orig_field)) {
        *orig_field = (char **) malloc (sizeof (char *));
        (*orig_field)[0] = 0;
      }
    }
  }
}

int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  struct generic_list * shape_list = NULL;
  struct generic_list * read_seeds_list = NULL;
  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "nossr",	0, NULL, 'r' },
        { "flanks",	1, NULL, 'f' },
        { "outfile",	1, NULL, 'o' },
        { "num-samples",	1, NULL, 'n' },
        { "num-samples-regression",	1, NULL, 'm' },
        { "precision",	1, NULL, 'p' },
        { "simulate",	0, NULL, 's' },
        { "verbose",	0, NULL, 'v' },
        { "mono",	0, NULL, 'i' },
        { "di",	0, NULL, 'd' },
        { "dna",	0, NULL, 'q' },
        { "rna",	0, NULL, 'u' },
        { "tstv",	0, NULL, 't' },
        { "kappa",	1, NULL, 'k' },
        { "gamma",	1, NULL, 'g' },
        { "print-tree",	0, NULL, 'b' },
        { "print-rates",	0, NULL, 'x' },
        { "clustal",	0, NULL, 0 },
        { "maf",	0, NULL, 0 },
        { "fasta",	0, NULL, 0 },
        { "oldAliEn",	0, NULL, 'a' },
        { "ribo",	0, NULL, 'j' },
        { "shape",	1, NULL, 0 },
        { "shapeMethod",	1, NULL, 0 },
        { "seed_with_pID",	0, NULL, 'y' },
        { "print_seeds",	0, NULL, 'z' },
        { "read_seeds",	1, NULL, 0 },
        { "sci",	0, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVrf:o:n:m:p:svidqutk:g:bxajyz", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->help_given),
              &(local_args_info.help_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "help", 'h',
              additional_error))
            goto failure;
          cmdline_parser_free (&local_args_info);
          return 0;
        
          break;
        case 'V':	/* Print version and exit.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->version_given),
              &(local_args_info.version_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "version", 'V',
              additional_error))
            goto failure;
          cmdline_parser_free (&local_args_info);
          return 0;
        
          break;
        case 'r':	/* No site specific rates.  */
        
        
          if (update_arg((void *)&(args_info->nossr_flag), 0, &(args_info->nossr_given),
              &(local_args_info.nossr_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "nossr", 'r',
              additional_error))
            goto failure;
        
          break;
        case 'f':	/* Flanking sites.  */
        
        
          if (update_arg( (void *)&(args_info->flanks_arg), 
               &(args_info->flanks_orig), &(args_info->flanks_given),
              &(local_args_info.flanks_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "flanks", 'f',
              additional_error))
            goto failure;
        
          break;
        case 'o':	/* Output filename.  */
        
        
          if (update_arg( (void *)&(args_info->outfile_arg), 
               &(args_info->outfile_orig), &(args_info->outfile_given),
              &(local_args_info.outfile_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "outfile", 'o',
              additional_error))
            goto failure;
        
          break;
        case 'n':	/* Number of samples.  */
        
        
          if (update_arg( (void *)&(args_info->num_samples_arg), 
               &(args_info->num_samples_orig), &(args_info->num_samples_given),
              &(local_args_info.num_samples_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "num-samples", 'n',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* Number of samples in regression.  */
        
        
          if (update_arg( (void *)&(args_info->num_samples_regression_arg), 
               &(args_info->num_samples_regression_orig), &(args_info->num_samples_regression_given),
              &(local_args_info.num_samples_regression_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "num-samples-regression", 'm',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* Cut-off for mononucleotide content (Euclidean distance of frequency vector).  */
        
        
          if (update_arg( (void *)&(args_info->precision_arg), 
               &(args_info->precision_orig), &(args_info->precision_given),
              &(local_args_info.precision_given), optarg, 0, 0, ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "precision", 'p',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* Simulate only.  */
        
        
          if (update_arg((void *)&(args_info->simulate_flag), 0, &(args_info->simulate_given),
              &(local_args_info.simulate_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "simulate", 's',
              additional_error))
            goto failure;
        
          break;
        case 'v':	/* verbose.  */
        
        
          if (update_arg((void *)&(args_info->verbose_flag), 0, &(args_info->verbose_given),
              &(local_args_info.verbose_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "verbose", 'v',
              additional_error))
            goto failure;
        
          break;
        case 'i':	/* Mononucleotide.  */
        
        
          if (update_arg((void *)&(args_info->mono_flag), 0, &(args_info->mono_given),
              &(local_args_info.mono_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "mono", 'i',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* Mononucleotide.  */
        
        
          if (update_arg((void *)&(args_info->di_flag), 0, &(args_info->di_given),
              &(local_args_info.di_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "di", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'q':	/* Print Us or Ts.  */
        
        
          if (update_arg((void *)&(args_info->dna_flag), 0, &(args_info->dna_given),
              &(local_args_info.dna_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "dna", 'q',
              additional_error))
            goto failure;
        
          break;
        case 'u':	/* Print Us or Ts.  */
        
        
          if (update_arg((void *)&(args_info->rna_flag), 0, &(args_info->rna_given),
              &(local_args_info.rna_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "rna", 'u',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* Transition/Transversion ratio.  */
        
        
          if (update_arg((void *)&(args_info->tstv_flag), 0, &(args_info->tstv_given),
              &(local_args_info.tstv_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "tstv", 't',
              additional_error))
            goto failure;
        
          break;
        case 'k':	/* kappa parameter.  */
        
        
          if (update_arg( (void *)&(args_info->kappa_arg), 
               &(args_info->kappa_orig), &(args_info->kappa_given),
              &(local_args_info.kappa_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "kappa", 'k',
              additional_error))
            goto failure;
        
          break;
        case 'g':	/* Categories for gamma for kappa ML estimation.  */
        
        
          if (update_arg( (void *)&(args_info->gamma_arg), 
               &(args_info->gamma_orig), &(args_info->gamma_given),
              &(local_args_info.gamma_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "gamma", 'g',
              additional_error))
            goto failure;
        
          break;
        case 'b':	/* Print estimated tree .  */
        
        
          if (update_arg((void *)&(args_info->print_tree_flag), 0, &(args_info->print_tree_given),
              &(local_args_info.print_tree_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "print-tree", 'b',
              additional_error))
            goto failure;
        
          break;
        case 'x':	/* Print rates to file (debugging).  */
        
        
          if (update_arg((void *)&(args_info->print_rates_flag), 0, &(args_info->print_rates_given),
              &(local_args_info.print_rates_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "print-rates", 'x',
              additional_error))
            goto failure;
        
          break;
        case 'a':	/* use old alifold energies (with gaps).  */
        
        
          if (update_arg((void *)&(args_info->oldAliEn_flag), 0, &(args_info->oldAliEn_given),
              &(local_args_info.oldAliEn_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "oldAliEn", 'a',
              additional_error))
            goto failure;
        
          break;
        case 'j':	/* use ribosum matrices.  */
        
        
          if (update_arg((void *)&(args_info->ribo_flag), 0, &(args_info->ribo_given),
              &(local_args_info.ribo_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "ribo", 'j',
              additional_error))
            goto failure;
        
          break;
        case 'y':	/* Seed with process ID (default=off).  */
        
        
          if (update_arg((void *)&(args_info->seed_with_pID_flag), 0, &(args_info->seed_with_pID_given),
              &(local_args_info.seed_with_pID_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "seed_with_pID", 'y',
              additional_error))
            goto failure;
        
          break;
        case 'z':	/* Print seed values  (default=off).  */
        
        
          if (update_arg((void *)&(args_info->print_seeds_flag), 0, &(args_info->print_seeds_given),
              &(local_args_info.print_seeds_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "print_seeds", 'z',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* Output format CLUSTAL W.  */
          if (strcmp (long_options[option_index].name, "clustal") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->clustal_flag), 0, &(args_info->clustal_given),
                &(local_args_info.clustal_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "clustal", '-',
                additional_error))
              goto failure;
          
          }
          /* Output format MAF.  */
          else if (strcmp (long_options[option_index].name, "maf") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->maf_flag), 0, &(args_info->maf_given),
                &(local_args_info.maf_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "maf", '-',
                additional_error))
              goto failure;
          
          }
          /* Output format FASTA.  */
          else if (strcmp (long_options[option_index].name, "fasta") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->fasta_flag), 0, &(args_info->fasta_given),
                &(local_args_info.fasta_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "fasta", '-',
                additional_error))
              goto failure;
          
          }
          /* Use SHAPE reactivity data to guide structure predicitons =file1,file2.  */
          else if (strcmp (long_options[option_index].name, "shape") == 0)
          {
          
            if (update_multiple_arg_temp(&shape_list, 
                &(local_args_info.shape_given), optarg, 0, 0, ARG_STRING,
                "shape", '-',
                additional_error))
              goto failure;
          
          }
          /* Specify the method how to convert SHAPE reactivity data to pseudo energy contributions =D[mX][bY].  */
          else if (strcmp (long_options[option_index].name, "shapeMethod") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->shapeMethod_arg), 
                 &(args_info->shapeMethod_orig), &(args_info->shapeMethod_given),
                &(local_args_info.shapeMethod_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "shapeMethod", '-',
                additional_error))
              goto failure;
          
          }
          /* set seed value(s) ={seed1(,seed2)}.  */
          else if (strcmp (long_options[option_index].name, "read_seeds") == 0)
          {
          
            if (update_multiple_arg_temp(&read_seeds_list, 
                &(local_args_info.read_seeds_given), optarg, 0, 0, ARG_STRING,
                "read_seeds", '-',
                additional_error))
              goto failure;
          
          }
          /* Calculate SCI.  */
          else if (strcmp (long_options[option_index].name, "sci") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->sci_flag), 0, &(args_info->sci_given),
                &(local_args_info.sci_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "sci", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */


  update_multiple_arg((void *)&(args_info->shape_arg),
    &(args_info->shape_orig), args_info->shape_given,
    local_args_info.shape_given, 0,
    ARG_STRING, shape_list);
  update_multiple_arg((void *)&(args_info->read_seeds_arg),
    &(args_info->read_seeds_orig), args_info->read_seeds_given,
    local_args_info.read_seeds_given, 0,
    ARG_STRING, read_seeds_list);

  args_info->shape_given += local_args_info.shape_given;
  local_args_info.shape_given = 0;
  args_info->read_seeds_given += local_args_info.read_seeds_given;
  local_args_info.read_seeds_given = 0;
  
  if (check_required)
    {
      error_occurred += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  free_list (shape_list, 1 );
  free_list (read_seeds_list, 1 );
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
